SLHA_TABLE="""
######################################################################
## PARAM_CARD AUTOMATICALY GENERATED BY MG5                       ####
######################################################################
###################################
## INFORMATION FOR CKMBLOCK
###################################
BLOCK CKMBLOCK # 
      1 2.277360e-01 # cabi
###################################
## INFORMATION FOR FRBLOCK
###################################
BLOCK FRBLOCK # 
      1 1.000000e+02 # qs
      2 2.000000e-05 # yheer
      3 2.000000e-05 # yhemur
      4 2.000000e-05 # yhetar
      5 2.000000e-02 # lams0h
      6 1.000000e-01 # lams0
###################################
## INFORMATION FOR MASS
###################################
BLOCK MASS # 
      1 5.040000e-03 # md
      2 2.550000e-03 # mu
      3 1.010000e-01 # ms
      4 1.270000e+00 # mc
      5 4.700000e+00 # mb
      6 1.720000e+02 # mt
      11 5.110000e-04 # me
      13 1.056600e-01 # mmu
      15 1.777000e+00 # mta
      23 9.118760e+01 # mz
      25 1.250000e+02 # mh
      255 1.250000e+02 # ms0
      1000101 125.1 # mhe
     -1000101 125.1 # mhe
      12 0.000000e+00 # ve : 0.0
      14 0.000000e+00 # vm : 0.0
      16 0.000000e+00 # vt : 0.0
      21 0.000000e+00 # g : 0.0
      22 0.000000e+00 # a : 0.0
      24 7.982436e+01 # w+ : cmath.sqrt(mz__exp__2/2. + cmath.sqrt(mz__exp__4/4. - (aew*cmath.pi*mz__exp__2)/(gf*sqrt__2)))
###################################
## INFORMATION FOR SMINPUTS
###################################
BLOCK SMINPUTS # 
      1 1.279000e+02 # aewm1
      2 1.166370e-05 # gf
      3 1.184000e-01 # as
###################################
## INFORMATION FOR YUKAWA
###################################
BLOCK YUKAWA # 
      1 5.040000e-03 # ymdo
      2 2.550000e-03 # ymup
      3 1.010000e-01 # yms
      4 1.270000e+00 # ymc
      5 4.700000e+00 # ymb
      6 1.720000e+02 # ymt
      11 5.110000e-04 # yme
      13 1.056600e-01 # ymm
      15 1.777000e+00 # ymtau
###################################
## INFORMATION FOR DECAY
###################################
DECAY 6 1.508336e+00 # wt
DECAY 23 2.495200e+00 # wz
DECAY 24 2.085000e+00 # ww
DECAY 25 5.000000e-03 # wh
DECAY 255 0.000000e+00 # ws0
DECAY 1000101 2.000000e-15 # wHE
      5.000000e-01 2 11 255 # br(~he -> e- ~s0)
      5.000000e-01 2 13 255 # br(~he -> mu- ~s0)
DECAY -1000101 2.000000e-15 # wHE
      5.000000e-01 2 -11 255 # br(~HE -> e+ ~s0)
      5.000000e-01 2 -13 255 # br(~HE -> mu+ ~s0)
DECAY 1 0.000000e+00 # d : 0.0
DECAY 2 0.000000e+00 # u : 0.0
DECAY 3 0.000000e+00 # s : 0.0
DECAY 4 0.000000e+00 # c : 0.0
DECAY 5 0.000000e+00 # b : 0.0
DECAY 11 0.000000e+00 # e- : 0.0
DECAY 12 0.000000e+00 # ve : 0.0
DECAY 13 0.000000e+00 # mu- : 0.0
DECAY 14 0.000000e+00 # vm : 0.0
DECAY 15 0.000000e+00 # ta- : 0.0
DECAY 16 0.000000e+00 # vt : 0.0
DECAY 21 0.000000e+00 # g : 0.0
DECAY 22 0.000000e+00 # a : 0.0
###################################
## INFORMATION FOR QNUMBERS 255
###################################
BLOCK QNUMBERS 255 #   ~s0
      1 0 # 3 times electric charge
      2 1 # number of spin states (2s+1)
      3 1 # colour rep (1: singlet, 3: triplet, 8: octet)
      4 0 # particle/antiparticle distinction (0=own anti)
###################################
## INFORMATION FOR QNUMBERS 1000101
###################################
BLOCK QNUMBERS 1000101 #   ~he
      1 -3 # 3 times electric charge
      2 2 # number of spin states (2s+1)
      3 1 # colour rep (1: singlet, 3: triplet, 8: octet)
      4 1 # particle/antiparticle distinction (0=own anti)
"""

import FWCore.ParameterSet.Config as cms

from Configuration.Generator.Pythia8CommonSettings_cfi import *
from Configuration.Generator.MCTunes2017.PythiaCP5Settings_cfi import *
from Configuration.Generator.PSweightsPythia.PythiaPSweightsSettings_cfi import *

generator = cms.EDFilter("Pythia8HadronizerFilter",
    maxEventsToPrint = cms.untracked.int32(1),
    pythiaPylistVerbosity = cms.untracked.int32(1),
    filterEfficiency = cms.untracked.double(1.0),
    pythiaHepMCVerbosity = cms.untracked.bool(False),
    SLHATableForPythia8 = cms.string('%s' % SLHA_TABLE),
    comEnergy = cms.double(13000.),
    PythiaParameters = cms.PSet(
        pythia8CommonSettingsBlock,
        pythia8CP5SettingsBlock,
        pythia8PSweightsSettingsBlock,
        ),
        parameterSets = cms.vstring('pythia8CommonSettings',
                                    'pythia8CP5Settings',
                                    'pythia8PSweightsSettings',
                                    )
    )
)

ProductionFilterSequence = cms.Sequence(generator)
