#!/usr/bin/env python
#from localOptionsAll import *
from localOptionsAODCtrlElec import *




BNTreeWt = 'events_puScaleFactor * events_muonScaleFactor * events_electronScaleFactor'   # excludes lumi weight, which is included automatically 

input_histograms = [
##     { 'channel'       : 'PreSelMuonMatchTrigMuonV2',
##       'varToPlot'     : 'mets_pt',
##       'histName'      : 'metsNumJets0',
##       'nbins'         : 100,
##       'xMin'          : 0,
##       'xMax'          : 500,
##       'cutString'     :'@jets_pt.size() == 0',
##       },

#    { 'channel'       : 'PreSelMuonMatchTrigMuonV2',
#      'varToPlot'     : 'mets_pt',
#      'histName'      : 'metsNumJets1',
#      'nbins'         : 100,
#      'xMin'          : 0,
#      'xMax'          : 500,
#      'cutString'     :'@jets_pt.size() == 1',
#            },
#    { 'channel'       : 'PreSelMuonMatchTrigMuonV2',
#       'varToPlot'     : 'mets_pt',
#       'histName'      : 'metsNumJets2',
#       'nbins'         : 100,
#       'xMin'          : 0,
#       'xMax'          : 500,
#       'cutString'     :'@jets_pt.size() == 2',
#                   },
##     { 'channel'       : 'PreSelMuonMatchTrigMuonV2',
##       'varToPlot'     : 'mets_pt',
##       'histName'      : 'metsNumJets3',
##       'nbins'         : 100,
##       'xMin'          : 0,
##       'xMax'          : 500,
##       'cutString'     :'@jets_pt.size() == 3',
##                         },
##     { 'channel'       : 'PreSelMuonMatchTrigMuonV2',
##       'varToPlot'     : 'mets_pt',
##       'histName'      : 'metsNumJets4',
##       'nbins'         : 100,
##       'xMin'          : 0,
##       'xMax'          : 500,
##       'cutString'     :'@jets_pt.size() == 4',
##       },


#################


     { 'channel'       : 'WToENuSimple',
       'varToPlot'     : '@muons_eta.size()',
       'histName'      : 'muonsSize',
       'nbins'         : 11,
       'xMin'          : -0.5,
       'xMax'          : 10.5,
       'cutString'     : BNTreeWt, 
       },


    { 'channel'       : 'WToENuSimple',
       'varToPlot'     : '@electrons_eta.size()',
       'histName'      : 'electronsSize',
       'nbins'         : 11,
       'xMin'          : -0.5,
       'xMax'          : 10.5,
       'cutString'     : BNTreeWt, 
       },

     { 'channel'       : 'WToENuSimple',
       'varToPlot'     : 'electrons_eta',
       'histName'      : 'electrons_eta',
       'nbins'         : 100,
       'xMin'          : -3,
       'xMax'          :  3,
       'cutString'     : BNTreeWt, 
       },



     { 'channel'       : 'WToENuSimple',
       'varToPlot'     : 'electrons_pt',
       'histName'      : 'electrons_pt',
       'nbins'         : 100,
       'xMin'          : 0,
       'xMax'          : 500,
       'cutString'     : BNTreeWt, 
       },

    { 'channel'       : 'WToENuSimple',
      'varToPlot'     : '@mets_pt.size()',
      'histName'      : 'metsSize',
      'nbins'         : 11,
      'xMin'          : -0.5,
      'xMax'          : 10.5,
      'cutString'     : BNTreeWt, 
      },

    { 'channel'       : 'WToENuSimple',
      'varToPlot'     : '@jets_pt.size()',
      'histName'      : 'jetsSize',
      'nbins'         : 15,
      'xMin'          : 0,
      'xMax'          : 15,
      'cutString'     : BNTreeWt,  
      },

    { 'channel'       : 'WToENuSimple',
      'varToPlot'     : 'jets_pt',
      'histName'      : 'jets_pt',
      'nbins'         : 100,
      'xMin'          : 0,
      'xMax'          : 500,
      'cutString'     : BNTreeWt,  
      },

    { 'channel'       : 'WToENuSimple',
      'varToPlot'     : 'mets_pt',
      'histName'      : 'mets_pt',
      'nbins'         : 100,
      'xMin'          : 0,
      'xMax'          : 500,
      'cutString'     : BNTreeWt, 
      },

    { 'channel'       : 'WToENuSimple',
      'varToPlot'     : 'mets_pt',
      'histName'      : 'mets_pt_cutNJets0',
      'nbins'         : 100,
      'xMin'          : 0,
      'xMax'          : 500,
      'cutString'     : '(@jets_pt.size() == 0 ) * ' + BNTreeWt,  
      },

    { 'channel'       : 'WToENuSimple',
      'varToPlot'     : 'mets_pt',
      'histName'      : 'mets_pt_cutNJets1',
      'nbins'         : 100,
      'xMin'          : 0,
      'xMax'          : 500,
      'cutString'     : '(@jets_pt.size() == 1 ) * ' + BNTreeWt,  
      },

    { 'channel'       : 'WToENuSimple',
      'varToPlot'     : 'fabs(fabs(fabs(mets_phi - electrons_phi) - 3.14159) - 3.14159)', 
      'histName'      : 'deltaPhi_metsVsElectron',  
      'nbins'         : 100, 
      'xMin'          : -0.2, 
      'xMax'          :  3.17, 
      'cutString'     : BNTreeWt,  
      },

    { 'channel'       : 'WToENuSimple',
      'varToPlot'     : 'fabs(fabs(fabs(mets_phi - electrons_phi) - 3.14159) - 3.14159)', 
      'histName'      : 'deltaPhi_metsVsElectron_NJets0',  
      'nbins'         : 100, 
      'xMin'          : -0.2, 
      'xMax'          :  3.17, 
      'cutString'     : '(@jets_pt.size() == 0 ) * ' + BNTreeWt,
      },

    { 'channel'       : 'WToENuSimple',
      'varToPlot'     : 'fabs(fabs(fabs(mets_phi - electrons_phi) - 3.14159) - 3.14159)', 
      'histName'      : 'deltaPhi_metsVsElectron_NJets1',  
      'nbins'         : 100, 
      'xMin'          : -0.2, 
      'xMax'          :  3.17, 
      'cutString'     : '(@jets_pt.size() == 1 ) * ' + BNTreeWt,
      },

    { 'channel'       : 'WToENuSimple',
      'varToPlot'     : 'fabs(fabs(fabs(mets_phi - electrons_phi) - 3.14159) - 3.14159)', 
      'histName'      : 'deltaPhi_metsVsElectron_NJets2',  
      'nbins'         : 100, 
      'xMin'          : -0.2, 
      'xMax'          :  3.17, 
      'cutString'     : '(@jets_pt.size() == 2 ) * ' + BNTreeWt,
      },

    { 'channel'       : 'WToENuSimple',
      'varToPlot'     : 'fabs(fabs(fabs(mets_phi - electrons_phi) - 3.14159) - 3.14159)', 
      'histName'      : 'deltaPhi_metsVsElectron_NJets3',  
      'nbins'         : 100, 
      'xMin'          : -0.2, 
      'xMax'          :  3.17, 
      'cutString'     : '(@jets_pt.size() >= 3 ) * ' + BNTreeWt,
      },


    { 'channel'       : 'WToENuSimple',
      'varToPlot'     : 'mets_pt',
      'histName'      : 'mets_pt_cutNJets23',
      'nbins'         : 100,
      'xMin'          : 0,
      'xMax'          : 500,
      'cutString'     : '(@jets_pt.size() >= 2 && @jets_pt.size() <= 3 ) * ' + BNTreeWt,  
      },

    { 'channel'       : 'WToENuSimple',
      'varToPlot'     : 'mets_pt',
      'histName'      : 'mets_pt_cutNJets45',
      'nbins'         : 100,
      'xMin'          : 0,
      'xMax'          : 500,
      'cutString'     : '(@jets_pt.size() >= 4 && @jets_pt.size() <= 5 ) * ' + BNTreeWt,  
      },

    { 'channel'       : 'WToENuSimple',
      'varToPlot'     : 'mets_pt',
      'histName'      : 'mets_pt_cutNJets67',
      'nbins'         : 100,
      'xMin'          : 0,
      'xMax'          : 500,
      'cutString'     : '(@jets_pt.size() >= 6 && @jets_pt.size() <= 7 ) * ' + BNTreeWt,  
      },

    { 'channel'       : 'WToENuSimple',
      'varToPlot'     : 'mets_pt',
      'histName'      : 'mets_pt_cutNJets8',
      'nbins'         : 100,
      'xMin'          : 0,
      'xMax'          : 500,
      'cutString'     : '(@jets_pt.size() >= 8 ) * ' + BNTreeWt,  
      },

    ## { 'channel'       : 'WToENuSimple',
    ##   'varToPlot'     : 'events_sample',  
    ##   'histName'      : 'events_sample', 
    ##   'nbins'         : 100,
    ##   'xMin'          : -100,
    ##   'xMax'          : 100,  
    ##   'cutString'     : BNTreeWt, 
    ##   },

##     { 'channel'       : 'WToENuSimple',
##       'varToPlot'     : 'events_run',  
##       'histName'      : 'events_run', 
##       'nbins'         : 100,
##       'xMin'          : 0,
##       'xMax'          : 1000000,  
##       'cutString'     : 'events_puScaleFactor * events_electronscaleFactor',  
##       },


##     { 'channel'       : 'WToENuSimple',
##       'varToPlot'     : 'events_puScaleFactor',  
##       'histName'      : 'events_puScaleFactor', 
##       'nbins'         : 100,
##       'xMin'          : 0,
##       'xMax'          : 5,  
##       'cutString'     :'',  
##       },

##     { 'channel'       : 'WToENuSimple',
##       'varToPlot'     : 'events_electronscaleFactor',  
##       'histName'      : 'events_electronscaleFactor', 
##       'nbins'         : 100,
##       'xMin'          : 0,
##       'xMax'          : 5,  
##       'cutString'     : '',  
##       },

##     { 'channel'       : 'WToENuSimple',
##       'varToPlot'     : 'events_electronScaleFactor',  
##       'histName'      : 'events_electronScaleFactor', 
##       'nbins'         : 100,
##       'xMin'          : 0,
##       'xMax'          : 5,  
##       'cutString'     : '',  
##       },


    { 'channel'       : 'WToENuSimple',
      'varToPlot'     : 'mets_pt',
      'histName'      : 'mets_pt_cutMT',
      'nbins'         : 100,
      'xMin'          : 0,
      'xMax'          : 500,
      'cutString'     : '( electrons_metMT > 50 ) * ' + BNTreeWt,  
      },

    { 'channel'       : 'WToENuSimple',
      'varToPlot'     : 'mets_pt',
      'histName'      : 'mets_pt_cutDeltaPhiElectronMet',
      'nbins'         : 100,
      'xMin'          : 0,
      'xMax'          : 500,
      'cutString'     : '( fabs(fabs(fabs(mets_phi - electrons_phi) - 3.14159) - 3.14159) > 2.0 ) * ' + BNTreeWt,  
      },

    { 'channel'       : 'WToENuSimple',
      'varToPlot'     : 'mets_pt',
      'histName'      : 'mets_pt_muonPhiLo',
      'nbins'         : 100,
      'xMin'          : 0,
      'xMax'          : 500,
      'cutString'     : '( fabs(electrons_phi) < 1.0 ) * ' + BNTreeWt,  
      },

    { 'channel'       : 'WToENuSimple',
      'varToPlot'     : 'mets_pt',
      'histName'      : 'mets_pt_muonPhiHi',
      'nbins'         : 100,
      'xMin'          : 0,
      'xMax'          : 500,
      'cutString'     : '( fabs(electrons_phi) > 2.0 ) * ' + BNTreeWt,  
      },

##      { 'channel'       : 'WToENuSimple',
##        'varToPlot'     : 'mets_pt',
##        'histName'      : 'mets_pt_looseHaloVeto',
##        'nbins'         : 100,
##        'xMin'          : 0,
##        'xMax'          : 500,
##        'cutString'     : '( events_CSCLooseHaloId == 0 ) * ' + BNTreeWt,  
##        },

##      { 'channel'       : 'WToENuSimple',
##        'varToPlot'     : 'events_CSCLooseHaloId',
##        'histName'      : 'events_CSCLooseHaloId',
##        'nbins'         : 11,
##        'xMin'          : -0.5,
##        'xMax'          : 10.5,
##        'cutString'     : BNTreeWt,  
##        },

##      { 'channel'       : 'WToENuSimple',
##        'varToPlot'     : 'mets_pt',
##        'histName'      : 'mets_pt_ElectronChargePlus',
##        'nbins'         : 100,
##        'xMin'          : 0,
##        'xMax'          : 500,
##        'cutString'     : '( electrons_charge  == 1 ) * ' + BNTreeWt,  
##        },

##      { 'channel'       : 'WToENuSimple',
##        'varToPlot'     : 'mets_pt',
##        'histName'      : 'mets_pt_ElectronChargeMinus',
##        'nbins'         : 100,
##        'xMin'          : 0,
##        'xMax'          : 500,
##        'cutString'     : '( electrons_charge  == -1 ) * ' + BNTreeWt,  
##        },

##      { 'channel'       : 'WToENuSimple',
##        'varToPlot'     : 'electrons_phi',
##        'histName'      : 'electrons_phi_isLooseHalo',
##        'nbins'         : 100,
##        'xMin'          : -3.15,
##        'xMax'          :  3.15,
##        'cutString'     : '( events_CSCLooseHaloId == 1 ) * ' + BNTreeWt,  
##        },

##      { 'channel'       : 'WToENuSimple',
##        'varToPlot'     : 'electrons_phi',
##        'histName'      : 'electrons_phi_isNotLooseHalo',
##        'nbins'         : 100,
##        'xMin'          : -3.15,
##        'xMax'          :  3.15,
##        'cutString'     : '( events_CSCLooseHaloId == 0 ) * ' + BNTreeWt,  
##        },

##      { 'channel'       : 'WToENuSimple',
##        'varToPlot'     : 'electrons_phi',
##        'histName'      : 'electrons_phi',
##        'nbins'         : 100,
##        'xMin'          : -3.15,
##        'xMax'          :  3.15,
##        'cutString'     : BNTreeWt,  
##        },

     { 'channel'       : 'WToENuSimple',
       'varToPlot'     : 'mets_phi',
       'histName'      : 'mets_phi',
       'nbins'         : 100,
       'xMin'          : -3.15,
       'xMax'          :  3.15,
       'cutString'     : BNTreeWt,  
       },


    ]


