import FWCore.ParameterSet.Config as cms
from DisappTrks.StandardAnalysis.utilities import *
from OSUT3Analysis.Configuration.pdgIdBins import *
from OSUT3Analysis.Configuration.cutUtilities import *

###############################################
##### Set up the histograms to be plotted #####
###############################################

#metBins = cms.untracked.vdouble(2000, 0.0, 10000.0)
#metBinsSlimmed = cms.untracked.vdouble(500, 0.0, 2500.0)
#deltaPhiBins = cms.untracked.vdouble(64, 0.0, 3.2)

FakeDecayHistograms = cms.PSet(
    inputCollection = cms.vstring("eventvariables"),
    histograms = cms.VPSet (
        cms.PSet (
            name = cms.string("puScaleFactor"),
            title = cms.string(";puScaleFactor"),
            binsX = cms.untracked.vdouble(50,0,5),
            inputVariables = cms.vstring("puScalingFactor"),   
        ),
        cms.PSet (
            name = cms.string("IsLeptonVeto"),
            title = cms.string(";passesVeto ; Number of Events"),
            binsX = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("passesVeto"),
        ),
        cms.PSet (
            name = cms.string("Overall deviation angle"),
            title = cms.string(";Deviation Angle [rad]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            inputVariables = cms.vstring("DeltaAngle"),
        ),
        cms.PSet (
            name = cms.string("MissOuter deviation angle"),
            title = cms.string(";Deviation Angle [rad]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            inputVariables = cms.vstring("MissOuterDeltaAngle"),
        ),
        cms.PSet (
            name = cms.string("DisTrk deviation angle"),
            title = cms.string(";Deviation Angle [rad]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            inputVariables = cms.vstring("DisTrkDeltaAngle"),
        ),
        cms.PSet (
            name = cms.string("Overall dR"),
            title = cms.string(";dR [rad]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            inputVariables = cms.vstring("DeltaR"),
        ),
        cms.PSet (
            name = cms.string("MissOuter dR"),
            title = cms.string(";dR [rad]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            inputVariables = cms.vstring("MissOuterDeltaR"),
        ),
        cms.PSet (
            name = cms.string("DisTrk dR"),
            title = cms.string(";dR [rad]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            inputVariables = cms.vstring("DisTrkDeltaR"),
        ),
        cms.PSet (
            name = cms.string("Overall Pprime"),
            title = cms.string(";P [GeV]"),
            binsX = cms.untracked.vdouble(100, 0.0, 100.0),
            inputVariables = cms.vstring("GenTrkMu"),
        ),
        cms.PSet (
            name = cms.string("MissOuter Pprime"),
            title = cms.string(";P [GeV]"),
            binsX = cms.untracked.vdouble(100, 0.0, 100.0),
            inputVariables = cms.vstring("MissOuterGenTrkMu"),
        ),
        cms.PSet (
            name = cms.string("DisTrk Pprime"),
            title = cms.string(";P [GeV]"),
            binsX = cms.untracked.vdouble(100, 0.0, 100.0),
            inputVariables = cms.vstring("DisTrkGenTrkMu"),
        ),
        cms.PSet (
            name = cms.string("Overall dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            inputVariables = cms.vstring("DeltaAngle", "DeltaP"),
        ),
        cms.PSet (
            name = cms.string("Overall PpdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 10.0),
            inputVariables = cms.vstring("DeltaAngle", "GenTrkMu"),
        ),
        cms.PSet (
            name = cms.string("Overall rPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#mu}/p^{#chi^{#pm}}"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 1.0),
            inputVariables = cms.vstring("DeltaAngle", "RatioP"),
        ),
        cms.PSet (
            name = cms.string("Overall NLnrPdAngle"),
            title = cms.string(";Deviation Angle [rad]; -Ln(p^{#mu}/p^{#chi^{#pm}})"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 10.0),
            inputVariables = cms.vstring("DeltaAngle", "NLnRatioP"),
        ),
        cms.PSet (
            name = cms.string("MissOuter dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            inputVariables = cms.vstring("MissOuterDeltaAngle", "MissOuterDeltaP"),
        ),
        cms.PSet (
            name = cms.string("MissOuter PpdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 10.0),
            inputVariables = cms.vstring("MissOuterDeltaAngle", "MissOuterGenTrkMu"),
        ),
        cms.PSet (
            name = cms.string("MissOuter rPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#mu}/p^{#chi^{#pm}}"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 1.0),
            inputVariables = cms.vstring("MissOuterDeltaAngle", "MissOuterRatioP"),
        ),
        cms.PSet (
            name = cms.string("MissOuter NLnrPdAngle"),
            title = cms.string(";Deviation Angle [rad]; -Ln(p^{#mu}/p^{#chi^{#pm}})"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 10.0),
            inputVariables = cms.vstring("MissOuterDeltaAngle", "MissOuterNLnRatioP"),
        ),
        cms.PSet (
            name = cms.string("DisTrk dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            inputVariables = cms.vstring("DisTrkDeltaAngle", "DisTrkDeltaP"),
        ),
        cms.PSet (
            name = cms.string("DisTrk PpdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 10.0),
            inputVariables = cms.vstring("DisTrkDeltaAngle", "DisTrkGenTrkMu"),
        ),
        cms.PSet (
            name = cms.string("DisTrk rPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#mu}/p^{#chi^{#pm}}"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 1.0),
            inputVariables = cms.vstring("DisTrkDeltaAngle", "DisTrkRatioP"),
        ),
        cms.PSet (
            name = cms.string("DisTrk NLnrPdAngle"),
            title = cms.string(";Deviation Angle [rad]; -Ln(p^{#mu}/p^{#chi^{#pm}})"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 10.0),
            inputVariables = cms.vstring("DisTrkDeltaAngle", "DisTrkNLnRatioP"),
        ),
        cms.PSet (
            name = cms.string("Overall dPtdAngle"),
            title = cms.string(";Deviation Angle [rad]; p_{T}^{#chi^{#pm}}-p_{T}^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            inputVariables = cms.vstring("DeltaAngle", "DeltaPt"),
        ),
        cms.PSet (
            name = cms.string("MissOuter dPtdAngle"),
            title = cms.string(";Deviation Angle [rad]; p_{T}^{#chi^{#pm}}-p_{T}^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            inputVariables = cms.vstring("MissOuterDeltaAngle", "MissOuterDeltaPt"),
        ),
        cms.PSet (
            name = cms.string("DisTrk dPtdAngle"),
            title = cms.string(";Deviation Angle [rad]; p_{T}^{#chi^{#pm}}-p_{T}^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            inputVariables = cms.vstring("DisTrkDeltaAngle", "DisTrkDeltaPt"),
        ),
        cms.PSet (
            name = cms.string("Overall dPdR"),
            title = cms.string(";dR [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            inputVariables = cms.vstring("DeltaR", "DeltaP"),
        ),
        cms.PSet (
            name = cms.string("MissOuter dPdR"),
            title = cms.string(";dR [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            inputVariables = cms.vstring("MissOuterDeltaR", "MissOuterDeltaP"),
        ),
        cms.PSet (
            name = cms.string("DisTrk dPdR"),
            title = cms.string(";dR [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            inputVariables = cms.vstring("DisTrkDeltaR", "DisTrkDeltaP"),
        ),
        cms.PSet (
            name = cms.string("Overall dPtdR"),
            title = cms.string(";dR [rad]; p_{T}^{#chi^{#pm}}-p_{T}^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            inputVariables = cms.vstring("DeltaR", "DeltaPt"),
        ),
        cms.PSet (
            name = cms.string("MissOuter dPtdR"),
            title = cms.string(";dR [rad]; p_{T}^{#chi^{#pm}}-p_{T}^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            inputVariables = cms.vstring("MissOuterDeltaR", "MissOuterDeltaPt"),
        ),
        cms.PSet (
            name = cms.string("DisTrk dPtdR"),
            title = cms.string(";dR [rad]; p_{T}^{#chi^{#pm}}-p_{T}^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            inputVariables = cms.vstring("DisTrkDeltaR", "DisTrkDeltaPt"),
        ),
   
        # Binned in eta
        cms.PSet (
            name = cms.string("DisTrk absEta0to0p4 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DisTrkDeltaAngle", "DisTrkDeltaP","( abs(GenTrkEta) < 0.4 )"),
        ),
        cms.PSet (
            name = cms.string("DisTrk absEta0p4to1 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DisTrkDeltaAngle", "DisTrkDeltaP","( abs(GenTrkEta) < 1 && abs(GenTrkEta)>0.4 )"),
        ),
        cms.PSet (
            name = cms.string("DisTrk absEta1to1p5 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DisTrkDeltaAngle", "DisTrkDeltaP","( abs(GenTrkEta) < 1.5 && abs(GenTrkEta) > 1 )"),
        ),
        cms.PSet (
            name = cms.string("DisTrk absEta1p5to2p1 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DisTrkDeltaAngle", "DisTrkDeltaP","( abs(GenTrkEta) < 2.1 && abs(GenTrkEta) > 1.5 )"),
        ),
        cms.PSet (
            name = cms.string("MissOuter absEta0to0p4 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("MissOuterDeltaAngle", "MissOuterDeltaP","( abs(GenTrkEta) < 0.4 )"),
        ),
        cms.PSet (
            name = cms.string("MissOuter absEta0p4to1 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("MissOuterDeltaAngle", "MissOuterDeltaP","( abs(GenTrkEta) < 1 && abs(GenTrkEta)>0.4 )"),
        ),
        cms.PSet (
            name = cms.string("MissOuter absEta1to1p5 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("MissOuterDeltaAngle", "MissOuterDeltaP","( abs(GenTrkEta) < 1.5 && abs(GenTrkEta) > 1 )"),
        ),
        cms.PSet (
            name = cms.string("MissOuter absEta1p5to2p1 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("MissOuterDeltaAngle", "MissOuterDeltaP","( abs(GenTrkEta) < 2.1 && abs(GenTrkEta) > 1.5 )"),
        ),
        cms.PSet (
            name = cms.string("Overall absEta0to0p4 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DeltaAngle", "DeltaP","( abs(GenTrkEta) < 0.4 )"),
        ),
        cms.PSet (
            name = cms.string("Overall absEta0p4to1 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DeltaAngle", "DeltaP","( abs(GenTrkEta) < 1 && abs(GenTrkEta)>0.4 )"),
        ),
        cms.PSet (
            name = cms.string("Overall absEta1to1p5 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DeltaAngle", "DeltaP","( abs(GenTrkEta) < 1.5 && abs(GenTrkEta) > 1 )"),
        ),
        cms.PSet (
            name = cms.string("Overall absEta1p5to2p1 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DeltaAngle", "DeltaP","( abs(GenTrkEta) < 2.1 && abs(GenTrkEta) > 1.5 )"),
        ),
          #Low pt range
        cms.PSet (
            name = cms.string("DisTrk GenPt40to60 absEta0to0p4 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DisTrkDeltaAngle", "DisTrkDeltaP","( GenTrkPt < 60 ) && ( GenTrkPt > 40 ) && ( abs(GenTrkEta) < 0.4 )"),
        ),
        cms.PSet (
            name = cms.string("DisTrk GenPt40to60 absEta0p4to1 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DisTrkDeltaAngle", "DisTrkDeltaP","( GenTrkPt < 60 ) && ( GenTrkPt > 40 ) && ( abs(GenTrkEta) < 1 && abs(GenTrkEta)>0.4 )"),
        ),
        cms.PSet (
            name = cms.string("DisTrk GenPt40to60 absEta1to1p5 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DisTrkDeltaAngle", "DisTrkDeltaP","( GenTrkPt < 60 ) && ( GenTrkPt > 40 ) && ( abs(GenTrkEta) < 1.5 && abs(GenTrkEta) > 1 )"),
        ),
        cms.PSet (
            name = cms.string("DisTrk GenPt40to60 absEta1p5to2p1 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DisTrkDeltaAngle", "DisTrkDeltaP","( GenTrkPt < 60 ) && ( GenTrkPt > 40 ) && ( abs(GenTrkEta) < 2.1 && abs(GenTrkEta) > 1.5 )"),
        ),
        cms.PSet (
            name = cms.string("MissOuter GenPt40to60 absEta0to0p4 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("MissOuterDeltaAngle", "MissOuterDeltaP","( GenTrkPt < 60 ) && ( GenTrkPt > 40 ) && ( abs(GenTrkEta) < 0.4 )"),
        ),
        cms.PSet (
            name = cms.string("MissOuter GenPt40to60 absEta0p4to1 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("MissOuterDeltaAngle", "MissOuterDeltaP","( GenTrkPt < 60 ) && ( GenTrkPt > 40 ) && ( abs(GenTrkEta) < 1 && abs(GenTrkEta)>0.4 )"),
        ),
        cms.PSet (
            name = cms.string("MissOuter GenPt40to60 absEta1to1p5 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("MissOuterDeltaAngle", "MissOuterDeltaP","( GenTrkPt < 60 ) && ( GenTrkPt > 40 ) && ( abs(GenTrkEta) < 1.5 && abs(GenTrkEta) > 1 )"),
        ),
        cms.PSet (
            name = cms.string("MissOuter GenPt40to60 absEta1p5to2p1 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("MissOuterDeltaAngle", "MissOuterDeltaP","( GenTrkPt < 60 ) && ( GenTrkPt > 40 ) && ( abs(GenTrkEta) < 2.1 && abs(GenTrkEta) > 1.5 )"),
        ),
        cms.PSet (
            name = cms.string("Overall GenPt40to60 absEta0to0p4 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DeltaAngle", "DeltaP","( GenTrkPt < 60 ) && ( GenTrkPt > 40 ) && ( abs(GenTrkEta) < 0.4 )"),
        ),
        cms.PSet (
            name = cms.string("Overall GenPt40to60 absEta0p4to1 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DeltaAngle", "DeltaP","( GenTrkPt < 60 ) && ( GenTrkPt > 40 ) && ( abs(GenTrkEta) < 1 && abs(GenTrkEta)>0.4 )"),
        ),
        cms.PSet (
            name = cms.string("Overall GenPt40to60 absEta1to1p5 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DeltaAngle", "DeltaP","( GenTrkPt < 60 ) && ( GenTrkPt > 40 ) && ( abs(GenTrkEta) < 1.5 && abs(GenTrkEta) > 1 )"),
        ),
        cms.PSet (
            name = cms.string("Overall GenPt40to60 absEta1p5to2p1 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DeltaAngle", "DeltaP","( GenTrkPt < 60 ) && ( GenTrkPt > 40 ) && ( abs(GenTrkEta) < 2.1 && abs(GenTrkEta) > 1.5 )"),
        ),
        # Binned in Momentum
        cms.PSet (
            name = cms.string("DisTrk GenP40to60 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DisTrkDeltaAngle", "DisTrkDeltaP","( GenTrkP < 60 ) && ( GenTrkP > 40 )"),
        ),
        cms.PSet (
            name = cms.string("DisTrk GenP60to80 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DisTrkDeltaAngle", "DisTrkDeltaP","( GenTrkP < 80 ) && ( GenTrkP > 60 )"),
        ),
        cms.PSet (
            name = cms.string("DisTrk GenP80to100 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DisTrkDeltaAngle", "DisTrkDeltaP","( GenTrkP < 100 ) && ( GenTrkP > 80 )"),
        ),
        cms.PSet (
            name = cms.string("DisTrk GenP100to120 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DisTrkDeltaAngle", "DisTrkDeltaP","( GenTrkP < 120 ) && ( GenTrkP > 100 )"),
        ),
        cms.PSet (
            name = cms.string("MissOuter GenP40to60 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("MissOuterDeltaAngle", "MissOuterDeltaP","( GenTrkP < 60 ) && ( GenTrkP > 40 )"),
        ),
        cms.PSet (
            name = cms.string("MissOuter GenP60to80 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("MissOuterDeltaAngle", "MissOuterDeltaP","( GenTrkP < 80 ) && ( GenTrkP > 60 )"),
        ),
        cms.PSet (
            name = cms.string("MissOuter GenP80to100 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("MissOuterDeltaAngle", "MissOuterDeltaP","( GenTrkP < 100 ) && ( GenTrkP > 80 )"),
        ),
        cms.PSet (
            name = cms.string("MissOuter GenP100to120 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("MissOuterDeltaAngle", "MissOuterDeltaP","( GenTrkP < 120 ) && ( GenTrkP > 100 )"),
        ),
        cms.PSet (
            name = cms.string("Overall GenP40to60 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DeltaAngle", "DeltaP","( GenTrkP < 60 ) && ( GenTrkP > 40 )"),
        ),
        cms.PSet (
            name = cms.string("Overall GenP60to80 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DeltaAngle", "DeltaP","( GenTrkP < 80 ) && ( GenTrkP > 60 )"),
        ),
        cms.PSet (
            name = cms.string("Overall GenP80to100 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DeltaAngle", "DeltaP","( GenTrkP < 100 ) && ( GenTrkP > 80 )"),
        ),
        cms.PSet (
            name = cms.string("Overall GenP100to120 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DeltaAngle", "DeltaP","( GenTrkP < 120 ) && ( GenTrkP > 100 )"),
        ),
        # Binned in Layers
        cms.PSet (
            name = cms.string("DisTrk BarrelL1 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DisTrkDeltaAngle", "DisTrkDeltaP","( abs(DecayVtxZ) < 30.197 ) && ( DecayVtxRho > 21.7 ) && ( DecayVtxRho < 24.9 )"),
        ),
        cms.PSet (
            name = cms.string("MissOuter BarrelL1 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("MissOuterDeltaAngle", "MissOuterDeltaP","( abs(DecayVtxZ) < 30.197 ) && ( DecayVtxRho > 21.7 ) && ( DecayVtxRho < 24.9 )"),
        ),
        cms.PSet (
            name = cms.string("Overall BarrelL1 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DeltaAngle", "DeltaP","( abs(DecayVtxZ) < 30.197 ) && ( DecayVtxRho > 21.7 ) && ( DecayVtxRho < 24.9 )"),
        ),
        cms.PSet (
            name = cms.string("DisTrk BarrelL2 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DisTrkDeltaAngle", "DisTrkDeltaP","( abs(DecayVtxZ) < 32.112 ) && ( DecayVtxRho > 30.45 ) && ( DecayVtxRho < 33.65 )"),
        ),
        cms.PSet (
            name = cms.string("MissOuter BarrelL2 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("MissOuterDeltaAngle", "MissOuterDeltaP","( abs(DecayVtxZ) < 32.112 ) && ( DecayVtxRho > 30.45 ) && ( DecayVtxRho < 33.65 )"),
        ),
        cms.PSet (
            name = cms.string("Overall BarrelL2 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DeltaAngle", "DeltaP","( abs(DecayVtxZ) < 32.112 ) && ( DecayVtxRho > 30.45 ) && ( DecayVtxRho < 33.65 )"),
        ),
        cms.PSet (
            name = cms.string("DisTrk BarrelL3 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DisTrkDeltaAngle", "DisTrkDeltaP","( abs(DecayVtxZ) < 67.846 ) && ( DecayVtxRho > 39.15 ) && ( DecayVtxRho < 42.35 )"),
        ),
        cms.PSet (
            name = cms.string("MissOuter BarrelL3 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("MissOuterDeltaAngle", "MissOuterDeltaP","( abs(DecayVtxZ) < 67.846 ) && ( DecayVtxRho > 39.15 ) && ( DecayVtxRho < 42.35 )"),
        ),
        cms.PSet (
            name = cms.string("Overall BarrelL3 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DeltaAngle", "DeltaP","( abs(DecayVtxZ) < 67.846 ) && ( DecayVtxRho > 39.15 ) && ( DecayVtxRho < 42.35 )"),
        ),
        cms.PSet (
            name = cms.string("DisTrk BarrelL4 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DisTrkDeltaAngle", "DisTrkDeltaP","( abs(DecayVtxZ) < 68.979 ) && ( DecayVtxRho > 47.9 ) && ( DecayVtxRho < 51.1 )"),
        ),
        cms.PSet (
            name = cms.string("MissOuter BarrelL4 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("MissOuterDeltaAngle", "MissOuterDeltaP","( abs(DecayVtxZ) < 68.979 ) && ( DecayVtxRho > 47.9 ) && ( DecayVtxRho < 51.1 )"),
        ),
        cms.PSet (
            name = cms.string("Overall BarrelL4 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DeltaAngle", "DeltaP","( abs(DecayVtxZ) < 68.979 ) && ( DecayVtxRho > 47.9 ) && ( DecayVtxRho < 51.1 )"),
        ),
        cms.PSet (
            name = cms.string("DisTrk BarrelL5 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DisTrkDeltaAngle", "DisTrkDeltaP","( abs(DecayVtxZ) < 69.722 ) && ( DecayVtxRho > 56.60 ) && ( DecayVtxRho < 59.80 )"),
        ),
        cms.PSet (
            name = cms.string("MissOuter BarrelL5 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("MissOuterDeltaAngle", "MissOuterDeltaP","( abs(DecayVtxZ) < 69.722 ) && ( DecayVtxRho > 56.60 ) && ( DecayVtxRho < 59.80 )"),
        ),
        cms.PSet (
            name = cms.string("Overall BarrelL5 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DeltaAngle", "DeltaP","( abs(DecayVtxZ) < 69.722 ) && ( DecayVtxRho > 56.60 ) && ( DecayVtxRho < 59.80 )"),
        ),
        cms.PSet (
            name = cms.string("DisTrk MECD1 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DisTrkDeltaAngle", "DisTrkDeltaP","( abs( abs(DecayVtxZ) - 51.8 ) < 0.5 ) && ( DecayVtxRho > 21.8 ) && ( DecayVtxRho < 35.40 )"),
        ),
        cms.PSet (
            name = cms.string("MissOuter MECD1 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("MissOuterDeltaAngle", "MissOuterDeltaP","( abs( abs(DecayVtxZ) - 51.8 ) < 0.5 ) && ( DecayVtxRho > 21.8 ) && ( DecayVtxRho < 35.40 )"),
        ),
        cms.PSet (
            name = cms.string("Overall MECD1 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DeltaAngle", "DeltaP","( abs( abs(DecayVtxZ) - 51.8 ) < 0.5 ) && ( DecayVtxRho > 21.8 ) && ( DecayVtxRho < 35.40 )"),
        ),
        cms.PSet (
            name = cms.string("DisTrk MECD2 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DisTrkDeltaAngle", "DisTrkDeltaP","( abs( abs(DecayVtxZ) - 63.4 ) < 0.5 ) && ( DecayVtxRho > 21.8 ) && ( DecayVtxRho < 35.40 )"),
        ),
        cms.PSet (
            name = cms.string("MissOuter MECD2 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("MissOuterDeltaAngle", "MissOuterDeltaP","( abs( abs(DecayVtxZ) - 63.4 ) < 0.5 ) && ( DecayVtxRho > 21.8 ) && ( DecayVtxRho < 35.40 )"),
        ),
        cms.PSet (
            name = cms.string("Overall MECD2 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DeltaAngle", "DeltaP","( abs( abs(DecayVtxZ) - 63.4 ) < 0.5 ) && ( DecayVtxRho > 21.8 ) && ( DecayVtxRho < 35.40 )"),
        ),
        cms.PSet (
            name = cms.string("DisTrk MECD3 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DisTrkDeltaAngle", "DisTrkDeltaP","( abs( abs(DecayVtxZ) - 75.0 ) < 0.5 ) && ( DecayVtxRho > 21.8 ) && ( DecayVtxRho < 35.40 )"),
        ),
        cms.PSet (
            name = cms.string("MissOuter MECD3 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("MissOuterDeltaAngle", "MissOuterDeltaP","( abs( abs(DecayVtxZ) - 75.0 ) < 0.5 ) && ( DecayVtxRho > 21.8 ) && ( DecayVtxRho < 35.40 )"),
        ),
        cms.PSet (
            name = cms.string("Overall MECD3 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DeltaAngle", "DeltaP","( abs( abs(DecayVtxZ) - 75.0 ) < 0.5 ) && ( DecayVtxRho > 21.8 ) && ( DecayVtxRho < 35.40 )"),
        ),
        cms.PSet (
            name = cms.string("DisTrk ECA1 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DisTrkDeltaAngle", "DisTrkDeltaP","( abs( abs(DecayVtxZ) - 95.2 ) < 0.5 ) && ( DecayVtxRho > 21.8 ) && ( DecayVtxRho < 60.80 )"),
        ),
        cms.PSet (
            name = cms.string("MissOuter ECA1 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("MissOuterDeltaAngle", "MissOuterDeltaP","( abs( abs(DecayVtxZ) - 95.2 ) < 0.5 ) && ( DecayVtxRho > 21.8 ) && ( DecayVtxRho < 60.80 )"),
        ),
        cms.PSet (
            name = cms.string("Overall ECA1 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DeltaAngle", "DeltaP","( abs( abs(DecayVtxZ) - 95.2 ) < 0.5 ) && ( DecayVtxRho > 21.8 ) && ( DecayVtxRho < 60.80 )"),
        ),
        cms.PSet (
            name = cms.string("DisTrk ECA2 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DisTrkDeltaAngle", "DisTrkDeltaP","( abs( abs(DecayVtxZ) - 104.2 ) < 0.5 ) && ( DecayVtxRho > 21.8 ) && ( DecayVtxRho < 60.80 )"),
        ),
        cms.PSet (
            name = cms.string("MissOuter ECA2 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("MissOuterDeltaAngle", "MissOuterDeltaP","( abs( abs(DecayVtxZ) - 104.2 ) < 0.5 ) && ( DecayVtxRho > 21.8 ) && ( DecayVtxRho < 60.80 )"),
        ),
        cms.PSet (
            name = cms.string("Overall ECA2 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DeltaAngle", "DeltaP","( abs( abs(DecayVtxZ) - 104.2 ) < 0.5 ) && ( DecayVtxRho > 21.8 ) && ( DecayVtxRho < 60.80 )"),
        ),
        cms.PSet (
            name = cms.string("DisTrk ECA3 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DisTrkDeltaAngle", "DisTrkDeltaP","( abs( abs(DecayVtxZ) - 114.7 ) < 0.5 ) && ( DecayVtxRho > 21.8 ) && ( DecayVtxRho < 60.80 )"),
        ),
        cms.PSet (
            name = cms.string("MissOuter ECA3 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("MissOuterDeltaAngle", "MissOuterDeltaP","( abs( abs(DecayVtxZ) - 114.7 ) < 0.5 ) && ( DecayVtxRho > 21.8 ) && ( DecayVtxRho < 60.80 )"),
        ),
        cms.PSet (
            name = cms.string("Overall ECA3 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DeltaAngle", "DeltaP","( abs( abs(DecayVtxZ) - 114.7 ) < 0.5 ) && ( DecayVtxRho > 21.8 ) && ( DecayVtxRho < 60.80 )"),
        ),
        cms.PSet (
            name = cms.string("DisTrk ECA4 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DisTrkDeltaAngle", "DisTrkDeltaP","( abs( abs(DecayVtxZ) - 129.3 ) < 0.5 ) && ( DecayVtxRho > 21.8 ) && ( DecayVtxRho < 60.80 )"),
        ),
        cms.PSet (
            name = cms.string("MissOuter ECA4 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("MissOuterDeltaAngle", "MissOuterDeltaP","( abs( abs(DecayVtxZ) - 129.3 ) < 0.5 ) && ( DecayVtxRho > 21.8 ) && ( DecayVtxRho < 60.80 )"),
        ),
        cms.PSet (
            name = cms.string("Overall ECA4 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DeltaAngle", "DeltaP","( abs( abs(DecayVtxZ) - 129.3 ) < 0.5 ) && ( DecayVtxRho > 21.8 ) && ( DecayVtxRho < 60.80 )"),
        ),
        cms.PSet (
            name = cms.string("DisTrk ECA5 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DisTrkDeltaAngle", "DisTrkDeltaP","( abs( abs(DecayVtxZ) - 144.1 ) < 0.5 ) && ( DecayVtxRho > 21.8 ) && ( DecayVtxRho < 60.80 )"),
        ),
        cms.PSet (
            name = cms.string("MissOuter ECA5 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("MissOuterDeltaAngle", "MissOuterDeltaP","( abs( abs(DecayVtxZ) - 144.1 ) < 0.5 ) && ( DecayVtxRho > 21.8 ) && ( DecayVtxRho < 60.80 )"),
        ),
        cms.PSet (
            name = cms.string("Overall ECA5 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DeltaAngle", "DeltaP","( abs( abs(DecayVtxZ) - 144.1 ) < 0.5 ) && ( DecayVtxRho > 21.8 ) && ( DecayVtxRho < 60.80 )"),
        ),
        cms.PSet (
            name = cms.string("DisTrk ECA6 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DisTrkDeltaAngle", "DisTrkDeltaP","( abs( abs(DecayVtxZ) - 163.0 ) < 0.5 ) && ( DecayVtxRho > 21.8 ) && ( DecayVtxRho < 60.80 )"),
        ),
        cms.PSet (
            name = cms.string("MissOuter ECA6 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("MissOuterDeltaAngle", "MissOuterDeltaP","( abs( abs(DecayVtxZ) - 163.0 ) < 0.5 ) && ( DecayVtxRho > 21.8 ) && ( DecayVtxRho < 60.80 )"),
        ),
        cms.PSet (
            name = cms.string("Overall ECA6 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DeltaAngle", "DeltaP","( abs( abs(DecayVtxZ) - 163.0 ) < 0.5 ) && ( DecayVtxRho > 21.8 ) && ( DecayVtxRho < 60.80 )"),
        ),
        cms.PSet (
            name = cms.string("DisTrk ECB1 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DisTrkDeltaAngle", "DisTrkDeltaP","( abs( abs(DecayVtxZ) - 182.3 ) < 0.5 ) && ( DecayVtxRho > 28.5 ) && ( DecayVtxRho < 60.80 )"),
        ),
        cms.PSet (
            name = cms.string("MissOuter ECB1 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("MissOuterDeltaAngle", "MissOuterDeltaP","( abs( abs(DecayVtxZ) - 182.3 ) < 0.5 ) && ( DecayVtxRho > 28.5 ) && ( DecayVtxRho < 60.80 )"),
        ),
        cms.PSet (
            name = cms.string("Overall ECB1 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DeltaAngle", "DeltaP","( abs( abs(DecayVtxZ) - 182.3 ) < 0.5 ) && ( DecayVtxRho > 28.5 ) && ( DecayVtxRho < 60.80 )"),
        ),
        cms.PSet (
            name = cms.string("DisTrk ECB2 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DisTrkDeltaAngle", "DisTrkDeltaP","( abs( abs(DecayVtxZ) - 206.8 ) < 0.5 ) && ( DecayVtxRho > 28.5 ) && ( DecayVtxRho < 60.80 )"),
        ),
        cms.PSet (
            name = cms.string("MissOuter ECB2 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("MissOuterDeltaAngle", "MissOuterDeltaP","( abs( abs(DecayVtxZ) - 206.8 ) < 0.5 ) && ( DecayVtxRho > 28.5 ) && ( DecayVtxRho < 60.80 )"),
        ),
        cms.PSet (
            name = cms.string("Overall ECB2 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DeltaAngle", "DeltaP","( abs( abs(DecayVtxZ) - 206.8 ) < 0.5 ) && ( DecayVtxRho > 28.5 ) && ( DecayVtxRho < 60.80 )"),
        ),
        cms.PSet (
            name = cms.string("DisTrk ECC1 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DisTrkDeltaAngle", "DisTrkDeltaP","( abs( abs(DecayVtxZ) - 231.9 ) < 0.5 ) && ( DecayVtxRho > 39.0 ) && ( DecayVtxRho < 60.80 )"),
        ),
        cms.PSet (
            name = cms.string("MissOuter ECC1 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("MissOuterDeltaAngle", "MissOuterDeltaP","( abs( abs(DecayVtxZ) - 231.9 ) < 0.5 ) && ( DecayVtxRho > 39.0 ) && ( DecayVtxRho < 60.80 )"),
        ),
        cms.PSet (
            name = cms.string("Overall ECC1 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DeltaAngle", "DeltaP","( abs( abs(DecayVtxZ) - 231.9 ) < 0.5 ) && ( DecayVtxRho > 39.0 ) && ( DecayVtxRho < 60.80 )"),
        ),
        cms.PSet (
            name = cms.string("DisTrk ECC2 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DisTrkDeltaAngle", "DisTrkDeltaP","( abs( abs(DecayVtxZ) - 263.8 ) < 0.5 ) && ( DecayVtxRho > 39.0 ) && ( DecayVtxRho < 60.80 )"),
        ),
        cms.PSet (
            name = cms.string("MissOuter ECC2 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("MissOuterDeltaAngle", "MissOuterDeltaP","( abs( abs(DecayVtxZ) - 263.8 ) < 0.5 ) && ( DecayVtxRho > 39.0 ) && ( DecayVtxRho < 60.80 )"),
        ),
        cms.PSet (
            name = cms.string("Overall ECC2 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DeltaAngle", "DeltaP","( abs( abs(DecayVtxZ) - 263.8 ) < 0.5 ) && ( DecayVtxRho > 39.0 ) && ( DecayVtxRho < 60.80 )"),
        ),
        cms.PSet (
            name = cms.string("DisTrk MSGCL1 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DisTrkDeltaAngle", "DisTrkDeltaP","( abs( DecayVtxZ ) < 120.5 ) && ( abs( DecayVtxRho - 74.7 ) < 1.5 ) "),
        ),
        cms.PSet (
            name = cms.string("MissOuter MSGCL1 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("MissOuterDeltaAngle", "MissOuterDeltaP","( abs( DecayVtxZ ) < 120.5 ) && ( abs( DecayVtxRho - 74.7 ) < 1.5 ) "),
        ),
        cms.PSet (
            name = cms.string("Overall MSGCL1 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DeltaAngle", "DeltaP","( abs( DecayVtxZ ) < 120.5 ) && ( abs( DecayVtxRho - 74.7 ) < 1.5 ) "),
        ),
        cms.PSet (
            name = cms.string("DisTrk MSGCL2 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DisTrkDeltaAngle", "DisTrkDeltaP","( abs( DecayVtxZ ) < 120.5 ) && ( abs( DecayVtxRho - 82.7 ) < 1.5 ) "),
        ),
        cms.PSet (
            name = cms.string("MissOuter MSGCL2 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("MissOuterDeltaAngle", "MissOuterDeltaP","( abs( DecayVtxZ ) < 120.5 ) && ( abs( DecayVtxRho - 82.7 ) < 1.5 ) "),
        ),
        cms.PSet (
            name = cms.string("Overall MSGCL2 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DeltaAngle", "DeltaP","( abs( DecayVtxZ ) < 120.5 ) && ( abs( DecayVtxRho - 82.7 ) < 1.5 ) "),
        ),
        cms.PSet (
            name = cms.string("DisTrk MSGCL3 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DisTrkDeltaAngle", "DisTrkDeltaP","( abs( DecayVtxZ ) < 120.5 ) && ( abs( DecayVtxRho - 90.7 ) < 1.5 ) "),
        ),
        cms.PSet (
            name = cms.string("MissOuter MSGCL3 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("MissOuterDeltaAngle", "MissOuterDeltaP","( abs( DecayVtxZ ) < 120.5 ) && ( abs( DecayVtxRho - 90.7 ) < 1.5 ) "),
        ),
        cms.PSet (
            name = cms.string("Overall MSGCL3 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DeltaAngle", "DeltaP","( abs( DecayVtxZ ) < 120.5 ) && ( abs( DecayVtxRho - 90.7 ) < 1.5 ) "),
        ),
        cms.PSet (
            name = cms.string("DisTrk MSGCL4 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DisTrkDeltaAngle", "DisTrkDeltaP","( abs( DecayVtxZ ) < 120.5 ) && ( abs( DecayVtxRho - 98.7 ) < 1.5 ) "),
        ),
        cms.PSet (
            name = cms.string("MissOuter MSGCL4 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("MissOuterDeltaAngle", "MissOuterDeltaP","( abs( DecayVtxZ ) < 120.5 ) && ( abs( DecayVtxRho - 98.7 ) < 1.5 ) "),
        ),
        cms.PSet (
            name = cms.string("Overall MSGCL4 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DeltaAngle", "DeltaP","( abs( DecayVtxZ ) < 120.5 ) && ( abs( DecayVtxRho - 98.7 ) < 1.5 ) "),
        ),
        cms.PSet (
            name = cms.string("DisTrk MSGCL5 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DisTrkDeltaAngle", "DisTrkDeltaP","( abs( DecayVtxZ ) < 120.5 ) && ( abs( DecayVtxRho - 106.7 ) < 1.5 ) "),
        ),
        cms.PSet (
            name = cms.string("MissOuter MSGCL5 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("MissOuterDeltaAngle", "MissOuterDeltaP","( abs( DecayVtxZ ) < 120.5 ) && ( abs( DecayVtxRho - 106.7 ) < 1.5 ) "),
        ),
        cms.PSet (
            name = cms.string("Overall MSGCL5 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DeltaAngle", "DeltaP","( abs( DecayVtxZ ) < 120.5 ) && ( abs( DecayVtxRho - 106.7 ) < 1.5 ) "),
        ),
        cms.PSet (
            name = cms.string("DisTrk MSGCL6 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DisTrkDeltaAngle", "DisTrkDeltaP","( abs( DecayVtxZ ) < 120.5 ) && ( abs( DecayVtxRho - 114.7 ) < 1.5 ) "),
        ),
        cms.PSet (
            name = cms.string("MissOuter MSGCL6 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("MissOuterDeltaAngle", "MissOuterDeltaP","( abs( DecayVtxZ ) < 120.5 ) && ( abs( DecayVtxRho - 114.7 ) < 1.5 ) "),
        ),
        cms.PSet (
            name = cms.string("Overall MSGCL6 dPdAngle"),
            title = cms.string(";Deviation Angle [rad]; p^{#chi^{#pm}}-p^{#mu} [GeV]"),
            binsX = cms.untracked.vdouble(64, 0.0, 3.2),
            binsY = cms.untracked.vdouble(100, 0.0, 100.0),
            binsZ = cms.untracked.vdouble(2, -0.5, 1.5),
            inputVariables = cms.vstring("DeltaAngle", "DeltaP","( abs( DecayVtxZ ) < 120.5 ) && ( abs( DecayVtxRho - 114.7 ) < 1.5 ) "),
        ),
    )
)




