name: Access Another Repo Workflow
on:
  push:
    branches:
      - main

jobs:
  access_repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v2
      
      - name: Checkout another repository
        uses: actions/checkout@v2
        with:
          repository: username/another-repo
          ref: main  # or specify a branch, tag, or commit hash